name: main
on:
  pull_request:
  push:
    branches: [master, main, 'test-me-*']
    tags: ['*']

jobs:
  main:
    strategy:
      matrix:
        include:
        - os: windows-latest
          py: 3.9
          toxenv: py
        - os: ubuntu-latest
          py: pypy3.9
          toxenv: py
        - os: ubuntu-latest
          py: 3.7
          toxenv: py
        - os: ubuntu-latest
          py: 3.8
          toxenv: py
        - os: ubuntu-latest
          py: 3.9
          toxenv: py
        - os: ubuntu-latest
          py: '3.10'
          toxenv: py
        - os: ubuntu-latest
          py: '3.11'
          toxenv: py
        - os: ubuntu-latest
          py: '3.12-dev'
          toxenv: py
        - os: ubuntu-latest
          py: 3.9
          toxenv: flake8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - run: pip install tox
    - run: tox -e ${{ matrix.toxenv }}
